/**
 * Browser→agent project-memory round-trip (Option B, cross-implementation).
 *
 * The operator authors a project memory IN THE BROWSER: the web wallet's WASM
 * (lastid-agent-wasm `sdkEncryptProjectContent`, Rust `project_content.rs`)
 * derives project_root_seed from ai_agent_seed, computes the opaque routing_id,
 * and seals the content in a LIDE SymmetricOnly envelope. The AGENT must read
 * those exact bytes with its own (Node) decrypt path — `project-crypto.js`.
 *
 * This test proves that round-trip across the two implementations using a
 * fixture emitted by the Rust browser-authoring path
 * (lastid-identity project_content.rs `emit_browser_authoring_fixture`,
 * `cargo test -p lastid-identity project_content -- --ignored --nocapture`).
 * If the Rust crypto or the Node crypto drifts, this fails — exactly the bug
 * (silent non-decryption of browser-authored memories) it guards.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';

import {
  deriveProjectRoutingId,
  decryptProjectJson,
  decryptProjectContent,
} from '../lib/project-crypto.js';
import { decodeRecord } from '../lib/agent-state-sync.js';
import { verifyRecordSignature } from '../lib/agent-sig-verify.js';

// ── Fixture: the browser authoring path, captured from Rust ──────────
// Generated by lastid-identity project_content.rs::emit_browser_authoring_fixture.
const FIXTURE = {
  aiAgentSeedHex: '1111111111111111111111111111111111111111111111111111111111111111',
  projectKey: 'github.com/acme/widgets',
  content: {
    kind: 'decision',
    claim: 'deploys go through staging first',
    subject: ['deploys'],
  },
  routingId: '1e502a2c1ebdf24ff8e409e2f01ae7bcdf209e278bc9078ce4608389537a1d87',
  envHex:
    '4c494445010003000001640000000410006167656e742d636f6e74656e742f76314c0000000000000000000000000000000000e93bc93b90a324c1139416940a548d532fbad558be6585f42b7bf6d54b930f3e087c61c5a03d72fc9ed604c64ae3f8e6e5418dd8471dc12e6ab67d8581ba26ed0a894e2181ade312e1c7f90ba682081861b6d0f4fd505b9350cbdb59a3afafada9a2a385a99c009a2478aa0c63400277b80d84f57e06773a7ef64fb45a89213eb84d279a48318a743ad11b9305bcb6f462417e2ec2ce1d339c4ca10e243a76200a53b128d510c0bc66de1a3f',
};

// PROJECT_MEMORY_ROOT_HKDF_INFO in lastid-identity v2.rs — the agent's
// project_root_seed (sealed at provisioning) is HKDF-SHA512 of ai_agent_seed
// under this label, the SAME derivation the browser uses. Computing it here
// locks that derivation: a wrong seed makes the routing_id parity check below
// fail before we even try to decrypt.
const PROJECT_MEMORY_ROOT_INFO = 'lastid/v2/project-memory-root';

function deriveProjectRootSeed(aiAgentSeed) {
  return Buffer.from(
    crypto.hkdfSync('sha512', aiAgentSeed, Buffer.alloc(0), Buffer.from(PROJECT_MEMORY_ROOT_INFO), 32),
  );
}

const aiAgentSeed = Buffer.from(FIXTURE.aiAgentSeedHex, 'hex');
const projectRootSeed = deriveProjectRootSeed(aiAgentSeed);
const env = Buffer.from(FIXTURE.envHex, 'hex');

test('Node derives the SAME routing_id as the browser (seed + HMAC parity)', () => {
  const routingId = deriveProjectRoutingId(projectRootSeed, FIXTURE.projectKey);
  assert.equal(routingId, FIXTURE.routingId);
});

test('agent decrypts a browser-authored project memory (round-trip)', () => {
  const decoded = decryptProjectJson(projectRootSeed, FIXTURE.routingId, env);
  assert.deepEqual(decoded, FIXTURE.content);
});

test('a peer WITHOUT the operator seed cannot read it', () => {
  const otherSeed = deriveProjectRootSeed(crypto.randomBytes(32));
  assert.throws(() => decryptProjectContent(otherSeed, FIXTURE.routingId, env));
});

test('the wrong routing_id (wrong content key) cannot read it', () => {
  const wrongRouting = deriveProjectRoutingId(projectRootSeed, 'github.com/acme/something-else');
  assert.throws(() => decryptProjectContent(projectRootSeed, wrongRouting, env));
});

// ── Operator authoring: the browser signs as the OPERATOR ────────────
// A browser-authored project record carries author='operator' and NO
// author_agent_did, signed with delegation_authority (ES256) — so the agent
// MUST verify it against the operator's delegation key, not an agent's Ed25519
// key. (The IdP records author='operator' for human-base-VC project writes; an
// agent-authored one is author='agent' + author_agent_did → EdDSA.) This is
// the agent-acceptance half of the round-trip, over the real browser bytes.
const envB64 = env.toString('base64')
const sha256Hex = (b) => crypto.createHash('sha256').update(b).digest('hex')
function mintEs256(claims, privateKey) {
  const h = Buffer.from(JSON.stringify({ typ: 'jwt+lastid-human-auth-v1', alg: 'ES256' })).toString('base64url')
  const p = Buffer.from(JSON.stringify(claims)).toString('base64url')
  const sig = crypto.sign('sha256', Buffer.from(`${h}.${p}`, 'utf8'), { key: privateKey, dsaEncoding: 'ieee-p1363' })
  return `${h}.${p}.${sig.toString('base64url')}`
}

test('agent ACCEPTS an operator-authored project record (ES256 verify + decode)', () => {
  const K = crypto.generateKeyPairSync('ec', { namedCurve: 'P-256' })
  const j = K.publicKey.export({ format: 'jwk' })
  const opJwk = { x_b64u: j.x, y_b64u: j.y }

  // The agent decodes the project ciphertext, then hashes the SAME plaintext
  // bytes the operator signed over.
  const record = {
    id: 'mem_proj_op', kind: 'memory', target: 'project', status: 'active', version: 1,
    routing_id: FIXTURE.routingId, enc_b64: envB64, author: 'operator',
  }
  const decoded = decodeRecord(record, null, projectRootSeed)
  const claims = {
    kind: 'memory', id: 'mem_proj_op', target: 'project', version: 1, status: 'active',
    content_sha256: sha256Hex(decoded.contentBytes),
  }
  record.sig = mintEs256(claims, K.privateKey)

  const res = verifyRecordSignature(record, decoded.contentBytes, opJwk, { agentDid: 'did:lastid:agent:zPeer' })
  assert.ok(res.ok, `expected verify ok, got ${JSON.stringify(res)}`)
})

test('a forged operator project record (wrong delegation key) is rejected', () => {
  const K = crypto.generateKeyPairSync('ec', { namedCurve: 'P-256' })
  const Wrong = crypto.generateKeyPairSync('ec', { namedCurve: 'P-256' })
  const wrongJwk = (() => { const j = Wrong.publicKey.export({ format: 'jwk' }); return { x_b64u: j.x, y_b64u: j.y } })()
  const record = {
    id: 'mem_proj_op', kind: 'memory', target: 'project', status: 'active', version: 1,
    routing_id: FIXTURE.routingId, enc_b64: envB64, author: 'operator',
  }
  const decoded = decodeRecord(record, null, projectRootSeed)
  record.sig = mintEs256(
    { kind: 'memory', id: 'mem_proj_op', target: 'project', version: 1, status: 'active', content_sha256: sha256Hex(decoded.contentBytes) },
    K.privateKey,
  )
  // Verify against a DIFFERENT operator key → fail-closed.
  const res = verifyRecordSignature(record, decoded.contentBytes, wrongJwk, { agentDid: 'did:lastid:agent:zPeer' })
  assert.equal(res.ok, false)
})
